# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2VhMzUzZTJiMTdmYzA2ZGZiMjIxZTc2ZTNiYjJkZjUwNjlmZDlkNjEyM2MyZGQ2Njg1Y2M2MTcxODdmMDJiNzYyMzg5OTBhOTBjNGZlMWUzNDJmZGQyZGM4YTA4NTI0NjNkODI5MzVkMGY3NDMwMGE4MjUzZDM1OWY3MTg1MWI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
